#!/usr/bin/env python3
"""Write a self-contained build brief for every forest asset, and an index of them.

A brief is everything a fresh model with no conversation history (for example after ``/compact``) needs to build
one asset with the forest Blender pipeline: Canva's own words for the object, the reference images, the numbers,
the palette, the commands, the acceptance checklist and the report format. Sources: the Canva manifest
(``assets/data/forest/forest_canva_objects.json``), the asset's profile (``profiles/forest_<asset>.json``) or, when
it has none, its spec (``forest_asset_specs.json``), and the resolved palette (``forest_palette.json``).

Usage::

    python3 tools/assets/forest_handoffs.py

Writes ``design/levels/forest/handoffs/NN_<asset>.md`` (NN is the Canva object number) and ``README.md`` there.
Re-run it after the manifest, a profile or a spec changes, and after a Canva sheet or a GLB appears, so the status
lines are current. The briefs are generated: edit this script or the data files, never a brief.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = REPO_ROOT / "assets" / "data" / "forest"
MANIFEST = DATA_DIR / "forest_canva_objects.json"
SPECS = DATA_DIR / "forest_asset_specs.json"
PALETTE = DATA_DIR / "forest_palette.json"
PROFILES_DIR = DATA_DIR / "profiles"
FOREST_DESIGN_DIR = REPO_ROOT / "design" / "levels" / "forest"
OUT_DIR = FOREST_DESIGN_DIR / "handoffs"
CANVA_DIR = FOREST_DESIGN_DIR / "canva"
VIEWS_DIR = CANVA_DIR / "views"
MOCKUP = REPO_ROOT / "design" / "levels" / "reference" / "forest" / "forest_biome_mockup.jpg"
SPRITES_DIR = REPO_ROOT / "design" / "levels" / "reference" / "forest" / "sprites"
GENERATORS_DIR = REPO_ROOT / "tools" / "blender" / "forest"
MODELS_DIR = REPO_ROOT / "assets" / "models" / "forest"
EVIDENCE_DIR = REPO_ROOT / "production" / "qa" / "evidence" / "forest"
SKIPPED = "skipped"

INTRO = """\
> This brief is self-contained: you do not need the conversation that produced it. Read all of it, then build.
> It is generated by `tools/assets/forest_handoffs.py`; do not edit it. The master brief with the whole pipeline
> is `design/levels/forest/HANDOFF.md`.
>
> **The Canva images are reference only.** You build the model yourself in Blender with a generator script you write
> (`bpy`/`bmesh`); nothing is converted from an image, and Canva or any image-to-3D service is not used to make geometry."""

CANVA_SHEET_HELP = """\
The Canva sheet is one 16:9 image: eight views of the object in two rows of four across the top 78 % (0, 45, 90,
135 degrees on the first row; 180, 225, 270, 315 on the second; 0 degrees is the front), camera slightly above, plain
grey background, and a caption bar at the bottom with the object's number, category, name and Canva's description of
what it drew. `python3 tools/assets/forest_canva_views.py <asset>` cuts it into `view_0.png` to `view_7.png` and
`caption.png` under `design/levels/forest/canva/views/<asset>/`, which are easier to inspect one by one."""

SOURCE_OF_TRUTH = """\
* The **mockup** is the source of truth for anything it shows. The **Canva sheet** is the source for the sides and
  back the mockup does not show, and for the 3D form. Canva is an image generator: its views may disagree with
  each other, and it sometimes adds things that are not in the mockup. Follow the majority of the views and the mockup.
* Do **not** model something only the Canva sheet invented (for example a chimney or a potted plant the mockup does
  not have). List it in your report under "Canva additions not built" so the orchestrator can decide.
* Every choice that neither the mockup nor the sheet settles is a **Proposal**: build the simplest plausible thing
  and list it in your report. Do not present an invention as something the references show."""

GENERATOR_SKELETON = """\
```python
\"\"\"<Title> (spec: <where the numbers come from>). One paragraph: what it is, origin, orientation.

Run headless::

    blender -b --factory-startup --python tools/blender/forest/<asset>.py -- --draft --preview DIR
\"\"\"
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import bmesh  # noqa: E402
import _shared as S  # noqa: E402


def build(profile: dict) -> list:
    \"\"\"Build the geometry; ``profile`` is the profile or spec dict. Return every object created.\"\"\"
    bm = bmesh.new()
    ...                                            # build geometry with bmesh; fixed seeds only
    body = S.mesh_from_bmesh("body", bm, "MF_Bark")
    marker = S.new_empty("place_example", (0, 0, 8.0))
    return [body, marker]


if __name__ == "__main__":
    # loads the profile or spec, builds, validates, exports, renders
    S.run("<asset>", build)
```"""

SHARED_API = """\
| Call | Use |
|---|---|
| `S.material(slot)`, `S.assign(obj, slot)` | Palette material for an `MF_*` slot; one material per slot per asset. |
| `S.mesh_from_bmesh(name, bm, slot=None)` | Bmesh to a linked mesh object; frees the bmesh. |
| `S.new_empty(name, location)` | Marker empty. Names: `attach_*`, `place_*`, `anchor_*`, `interact_*`, `water_<n>`. |
| `S.shade_smooth_by_angle(obj, degrees)` | Smooth shading with crisp edges beyond an angle. |
| `S.ground_tile_material()`, `S.set_vertex_colors(obj, srgb_per_vertex)` | Vertex-coloured ground (`MF_GroundTile`): one sRGB colour per vertex, exported as `COLOR_0`. |
| `S.light_shaft_material(alpha, strength)` | The emissive, alpha-blended `MF_LightShaft` material. |
| `S.load_profile(name)`, `S.report(profile)`, `S.render_views(dir, name)` | Used by `run`; call them directly only if you need to. |
| `S.run(name, build)` | Standard `main`. Fails if the triangle budget is exceeded, a material is not an allowed slot, a mesh has no material or an unapplied transform. A size outside +-35 % of the estimate is only a warning. Flags after `--`: `--draft` (do not write the GLB), `--preview DIR` (render eight views), `--out DIR`. |"""

RULES = """\
* **Deterministic.** Fixed random seeds; the same script gives the same GLB.
* **Units and axes.** 1 unit = 1 m, Z up, the front faces Blender -Y (Godot +Z). Put the origin where the spec says. Apply all transforms.
* **Materials.** Only the `MF_*` slots (and `MF_GroundTile` / `MF_LightShaft` via the helpers). Never type a colour by hand. Merge static meshes that share a material.
* **Geometry, not cards.** Thin crisp features (rope, leaf edges, planks) are real geometry, not alpha cards, so the toon shader works and the web build stays simple. The only alpha material is `MF_LightShaft`.
* **Silhouette first.** If you are debating detail against silhouette, choose silhouette. Chunky, slightly irregular, hand-made proportions match the mockup; do not make it neat.
* **Triangle budget.** Render triangles only; collision proxies do not count. Stay under the budget in section 4.
* **Collision.** A simple proxy mesh named `<asset>-colonly` (trimesh) or `<asset>-convcolonly` (convex hull) becomes Godot collision. Proxies are excluded from the budget and from the preview.
* **Markers.** Empties named as the spec says, at the positions the spec says.
* **Files you may write:** `tools/blender/forest/<asset>.py`, `assets/models/forest/<asset>.glb` (and the `.glb.import` Godot creates), `production/qa/evidence/forest/<asset>_review.png`. **Do not edit** `_shared.py`, `palette.py`, `review_sheet.py`, `tools/blender/common/`, any other asset's script, or any data file. If the pipeline blocks you, stop and report exactly what is missing.
* **Do not** call Canva, do not use Meshy or any image-to-3D service, do not run `git commit` or `git push` (the orchestrator does). Do not delete files by variable path: use a new scratch folder per iteration.
* **Interruptions.** A user interruption stops you without warning and loses everything not on disk. Write the generator file early and keep it runnable after every edit."""

COMMANDS = """\
```bash
SCRATCH=<your session scratchpad directory>/<asset>/v1     # a NEW folder per iteration (v2, v3, ...)
mkdir -p "$SCRATCH"

# iterate: validates, renders eight views, does NOT write the GLB (about 30 s for a simple asset)
blender -b --factory-startup --python tools/blender/forest/<asset>.py -- --draft --preview "$SCRATCH"
python3 tools/blender/forest/review_sheet.py <asset> --renders "$SCRATCH" --out "$SCRATCH/review.png"
# open $SCRATCH/review.png with the Read tool; read the VALIDATION line the Blender run printed

# final: also writes assets/models/forest/<asset>.glb, then keep the review sheet as evidence
blender -b --factory-startup --python tools/blender/forest/<asset>.py -- --preview "$SCRATCH"
python3 tools/blender/forest/review_sheet.py <asset> --renders "$SCRATCH" --out production/qa/evidence/forest/<asset>_review.png

# Godot import: creates assets/models/forest/<asset>.glb.import (an error about a missing sky_village.tscn is old and not yours)
godot --headless --path . --import
```
The review sheet shows the mockup sprite (if this asset has one) and the Canva 360 sheet (if it exists) above the
eight renders of your model. Read it after **every** change and compare silhouette, proportions, colour and detail."""

CHECKLIST = """\
- [ ] `tools/blender/forest/<asset>.py` exists: module docstring with the run commands, deterministic, no dead code, no debug prints beyond `run`'s own.
- [ ] The Blender run printed `VALIDATION` with `"ok": true`, triangles within the budget, no unknown material slots, no unapplied transforms; every warning is explained in the report.
- [ ] `assets/models/forest/<asset>.glb` exists and `assets/models/forest/<asset>.glb.import` was created by the Godot import.
- [ ] Origin, orientation and size match section 4; the front faces Blender -Y.
- [ ] The collision proxy and the markers in section 4 exist with the exact names (or the spec says none).
- [ ] `production/qa/evidence/forest/<asset>_review.png` is the review sheet of the final build, and you looked at it.
- [ ] You compared the eight renders with the Canva sheet and the mockup, and every remaining difference is in the report.
- [ ] Nothing outside the files you may write (section 5) was changed: check `git status`."""

REPORT_FORMAT = """\
Reply with this, in this order, at most about 30 lines, in plain words:

1. **Result**: built / partly built / blocked, and the files you wrote (paths).
2. **Numbers**: triangles used / budget, dimensions x / y / z in metres, markers, collision proxy.
3. **Matches**: what matches the Canva sheet and the mockup.
4. **Differences**: what does not, and why (budget, ambiguity, a Canva view that contradicts another).
5. **Proposals**: every choice the references did not settle.
6. **Canva additions not built**: things the Canva sheet shows that the mockup does not.
7. **Open questions** for the orchestrator, or "none"."""


def slug(text: str) -> str:
    """Lower-case ``text`` with every run of non-alphanumerics turned into one underscore."""
    return re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")


def cell(text: object) -> str:
    """``text`` made safe for a Markdown table cell."""
    return str(text).replace("|", "\\|").replace("\n", " ")


def rel(path: Path) -> str:
    """``path`` relative to the repository, with forward slashes."""
    return path.relative_to(REPO_ROOT).as_posix()


def load_json(path: Path) -> dict:
    """The JSON document at ``path``."""
    return json.loads(path.read_text(encoding="utf-8"))


def identification_sheet(canva_id: int, sheets: list[dict]) -> Path:
    """The identification sheet listing object ``canva_id``; ``sheets`` are the manifest entries such as ``{"objects": "1-22"}``."""
    for sheet in sheets:
        first, last = (int(n) for n in sheet["objects"].split("-"))
        if first <= canva_id <= last:
            return REPO_ROOT / sheet["file"]
    raise SystemExit(f"no identification sheet lists Canva object {canva_id}")


def canva_sheet_path(obj: dict) -> Path:
    """Where the 360-degree sheet of ``obj`` is (or will be) saved."""
    if obj.get("turnaround"):
        return REPO_ROOT / obj["turnaround"]["image"]
    return CANVA_DIR / f"{obj['canva_id']:02d}_{slug(obj['name'])}_360.png"


def build_state(asset: str) -> str:
    """``built`` when a GLB exists, ``draft`` when only a generator does, else ``not started``."""
    if (MODELS_DIR / f"{asset}.glb").exists():
        return "built"
    if (GENERATORS_DIR / f"{asset}.py").exists():
        return "draft"
    return "not started"


def build_source(asset: str, specs: dict) -> tuple[str, dict]:
    """``("profile", data)`` when the asset has a profile, else ``("spec", data)``."""
    profile_path = PROFILES_DIR / f"forest_{asset}.json"
    if profile_path.exists():
        return "profile", load_json(profile_path)
    return "spec", specs[asset]


def normalise(source: str, data: dict) -> dict:
    """The fields the brief prints, from a profile or a spec."""
    if source == "profile":
        return {
            "kind": data["kind"], "size_m": data["size_m"], "size_note": data.get("size_note"), "origin": data["origin"],
            "triangle_budget": data["triangle_budget"], "materials": data["materials"],
            "collision": data["godot"]["collision"], "markers": data["godot"]["markers"],
            "depends_on": [], "extends": None, "build_notes": None,
        }
    return {
        "kind": data["kind"], "size_m": data["size_m"], "size_note": None, "origin": data["origin"],
        "triangle_budget": data["triangle_budget"], "materials": data["materials"],
        "collision": data["collision"], "markers": data["markers"],
        "depends_on": data["depends_on"], "extends": data["extends"], "build_notes": data["build_notes"],
    }


def state_line(asset: str, state: str) -> str:
    """One sentence telling the builder whether work already exists."""
    generator = f"`{rel(GENERATORS_DIR / f'{asset}.py')}`"
    if state == "built":
        return (f"A first build exists (`{rel(MODELS_DIR / f'{asset}.glb')}`, generator {generator}). "
                "Do not start over: review it against the references below, find what is wrong, and refine the generator.")
    if state == "draft":
        return (f"An unfinished generator exists ({generator}) but no GLB. Read it, keep what is right, "
                "finish or rewrite it.")
    return "Nothing exists yet for this asset."


def references_section(obj: dict, source: str, data: dict, sheets: list[dict]) -> list[str]:
    """Section 3: every reference image with its path and whether the file exists."""
    asset = obj["asset"]
    sheet = canva_sheet_path(obj)
    views = VIEWS_DIR / asset
    ident = identification_sheet(obj["canva_id"], sheets)
    rows = [
        ("Canva 360-degree sheet with caption", sheet, "exists" if sheet.exists() else "NOT GENERATED YET (see below)"),
        ("Canva sheet cut into views", views, "exists" if views.exists() else "not cut yet"),
        ("Whole mockup (the art style and the truth)", MOCKUP, "exists"),
        (f"Canva identification sheet holding object {obj['canva_id']}", ident, "exists"),
    ]
    lines = ["| Reference | Path | State |", "|---|---|---|"]
    lines += [f"| {cell(name)} | `{rel(path)}` | {state} |" for name, path, state in rows]
    if source == "profile":
        sprite = data["sprite"]
        sprite_png = SPRITES_DIR / f"{asset}.png"
        lines.append(f"| Mockup crop (sprite) | `{rel(sprite_png)}` | {'exists' if sprite_png.exists() else 'missing'} |")
        lines += ["", f"The sprite is the box `{sprite['crop']}` (x0, y0, x1, y1 pixels) of the 1200 x 896 mockup. "
                  f"It shows: {sprite['shows']}.", "",
                  f"Where to find it in the whole mockup: {data['where_in_image']}."]
        for extra in data.get("sprite_extra", []):
            lines.append(f"* Further crop `{extra['name']}` {extra['crop']}: {extra['shows']}.")
    else:
        lines += ["", "This object has no sprite crop. Find it in the whole mockup and on the identification sheet "
                  f"(object {obj['canva_id']}). Hint from the checks made so far: {obj['mockup_note']}"]
    lines += ["", CANVA_SHEET_HELP.replace("<asset>", asset), ""]
    if not sheet.exists():
        lines += [
            "**The Canva sheet has not been generated for this object yet.** The orchestrator makes it with the Canva tool "
            "(subagents have no Canva access). Build from the description, the numbers, the mockup and the identification "
            "sheet, say in your report that no sheet was available, and expect a follow-up pass against the sheet once it exists.",
            "",
        ]
    return lines


def spec_section(asset: str, source: str, data: dict, fields: dict) -> list[str]:
    """Section 4: the numbers and the description."""
    size = fields["size_m"]
    origin_of_numbers = f"`assets/data/forest/profiles/forest_{asset}.json`" if source == "profile" else \
        f"`assets/data/forest/forest_asset_specs.json`, key `{asset}`"
    lines = [
        f"Numbers come from {origin_of_numbers}; read it too. Sizes are estimates scaled to a 1.7 m trainer (Blender axes: x width, y depth, z height).",
        "",
        "| Field | Value |", "|---|---|",
        f"| Kind | {fields['kind']} |",
        f"| Size x / y / z | {size['x']} / {size['y']} / {size['z']} m |",
        f"| Origin and facing | {cell(fields['origin'])} |",
        f"| Triangle budget | {fields['triangle_budget']:,} render triangles |",
        f"| Materials | {', '.join(f'`{m}`' for m in fields['materials'])} |",
        f"| Collision | {cell(fields['collision'])} |",
        f"| Markers | {cell('; '.join(fields['markers'])) if fields['markers'] else 'none'} |",
        f"| Output | `{rel(MODELS_DIR / f'{asset}.glb')}` |",
    ]
    if fields["size_note"]:
        lines += ["", f"Size note: {fields['size_note']}"]
    if fields["extends"]:
        lines += ["", f"**Extends a finished asset:** `{fields['extends']}` (read it first)."]
    if fields["depends_on"]:
        parts = ", ".join(f"`{rel(MODELS_DIR / f'{part}.glb')}` ({'exists' if (MODELS_DIR / f'{part}.glb').exists() else 'NOT BUILT YET'})"
                          for part in fields["depends_on"])
        lines += ["", f"**Depends on finished parts:** {parts}. If a part's GLB does not exist, stop and report which one."]
    if source == "profile":
        lines += ["", "### Description", "", data["description"], "", "### Look (each line says what it is based on)", "",
                  "| Feature | Basis |", "|---|---|"]
        lines += [f"| {cell(item['feature'])} | {cell(item['basis'])} |" for item in data["look"]]
        lines += ["", "**Not visible in the sprite** (build these as the `Proposal` lines say and report them): "
                  + "; ".join(data["not_in_sprite"]) + ".", "",
                  f"**What the Canva sheet must show / what belongs to the object:** {data['turnaround_focus']}."]
    else:
        lines += ["", "### Build notes", "", fields["build_notes"]]
    return lines


def palette_section(materials: list[str], palette: dict) -> list[str]:
    """Section 5's palette table for the slots the asset uses."""
    lines = ["| Slot | base | lit | shadow | roughness | Used for |", "|---|---|---|---|---|---|"]
    for slot in materials:
        entry = palette["slots"].get(slot)
        if entry is None:
            lines.append(f"| `{slot}` | helper material | | | | see the `S.` helper in the API table |")
            continue
        lines.append(f"| `{slot}` | {entry['base']} | {entry.get('lit', '')} | {entry.get('shadow', '')} | "
                     f"{entry['roughness']} | {cell(entry['use'])} |")
    return lines


def render_brief(obj: dict, specs: dict, palette: dict, sheets: list[dict]) -> str:
    """The whole Markdown brief of one object."""
    asset = obj["asset"]
    source, data = build_source(asset, specs)
    fields = normalise(source, data)
    caption = obj["turnaround"]["caption"] if obj.get("turnaround") else None
    lines = [
        f"# Build brief: {obj['name']} (`{asset}`)", "", INTRO, "",
        "## 1. Mission", "",
        f"Build the game-ready 3D model **`{asset}`** (Canva object #{obj['canva_id']}, category {obj['category']}) as a "
        f"Godot 4.7.2 GLB, in the forest biome's painterly storybook art style, with a Blender generator script. "
        f"{state_line(asset, build_state(asset))}", "",
        "## 2. What Canva says this object is", "",
        f"* **Canva name:** {obj['name']}",
        f"* **Canva description (verbatim):** {obj['canva_description']}",
        f"* **Description Canva wrote under its 360-degree sheet (verbatim):** {caption if caption else 'not generated yet'}",
        f"* **Checked against the mockup:** `{obj['mockup_check']}`. {obj['mockup_note']}", "",
        "How to weigh the sources:", "", SOURCE_OF_TRUTH, "",
        "## 3. Reference images", "", "Open every existing image with the Read tool before you model.", "",
        *references_section(obj, source, data, sheets),
        "## 4. What to build", "",
        *spec_section(asset, source, data, fields), "",
        "## 5. How to build it", "",
        "1. Read this whole brief and look at every reference image in section 3.",
        "2. Read one finished sibling generator for the house style: `tools/blender/forest/rope_bridge.py` (structure) "
        "or `tools/blender/forest/fern.py` (plant); `tools/blender/forest/_shared.py` holds the helpers.",
        f"3. Write `tools/blender/forest/{asset}.py` early and keep it runnable after every edit.",
        "4. Iterate with the draft command; read the review sheet after every change.",
        "5. When the model matches, run the final command, then the Godot import.",
        "6. Fill the checklist in section 6 and reply in the format of section 7.", "",
        "### Commands", "", COMMANDS.replace("<asset>", asset), "",
        "### Palette for this asset", "", "Colours measured from the mockup (`assets/data/forest/forest_palette.json`); "
        "use the slot, never the hex. `lit` and `shadow` are the toon-ramp pair. Ground tiles are coloured per vertex "
        "from these hexes with `S.set_vertex_colors`.", "",
        *palette_section(fields["materials"], palette), "",
        "### Skeleton of a generator", "", GENERATOR_SKELETON.replace("<asset>", asset), "",
        "### `_shared.py` helpers (import as `S`)", "", SHARED_API, "",
        "### Rules", "", RULES.replace("<asset>", asset), "",
        "## 6. Acceptance checklist", "", CHECKLIST.replace("<asset>", asset), "",
        "## 7. Report format", "", REPORT_FORMAT, "",
    ]
    return "\n".join(lines)


def render_index(entries: list[dict]) -> str:
    """The README listing every brief with the state of its sheet and build."""
    lines = [
        "# Forest asset build briefs", "",
        "Generated by `tools/assets/forest_handoffs.py` (state as of the last run). One self-contained brief per asset: "
        "hand a brief to a builder model as its whole task. Start with the master brief, "
        "`design/levels/forest/HANDOFF.md`, for the pipeline and how to spawn a builder.", "",
        "| # | Category | Canva name | Asset | Size x / y / z (m) | Budget | Canva sheet | Build | Brief |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for entry in entries:
        size = entry["size_m"]
        lines.append(f"| {entry['canva_id']} | {entry['category']} | {cell(entry['name'])} | `{entry['asset']}` | "
                     f"{size['x']} / {size['y']} / {size['z']} | {entry['triangle_budget']:,} | {entry['sheet']} | "
                     f"{entry['build']} | [{entry['file']}]({entry['file']}) |")
    lines += ["", f"{len(entries)} briefs."]
    return "\n".join(lines) + "\n"


def main() -> int:
    manifest = load_json(MANIFEST)
    specs = load_json(SPECS)["specs"]
    palette = load_json(PALETTE)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    entries = []
    for obj in manifest["objects"]:
        if not obj["asset"] or obj["status"] == SKIPPED:
            continue
        brief = f"{obj['canva_id']:02d}_{obj['asset']}.md"
        (OUT_DIR / brief).write_text(render_brief(obj, specs, palette, manifest["sheets"]), encoding="utf-8")
        fields = normalise(*build_source(obj["asset"], specs))
        entries.append({
            "canva_id": obj["canva_id"], "category": obj["category"], "name": obj["name"], "asset": obj["asset"],
            "size_m": fields["size_m"], "triangle_budget": fields["triangle_budget"],
            "sheet": "ready" if canva_sheet_path(obj).exists() else "missing", "build": build_state(obj["asset"]),
            "file": brief,
        })
    (OUT_DIR / "README.md").write_text(render_index(entries), encoding="utf-8")
    print(f"wrote {len(entries)} briefs and README.md to {rel(OUT_DIR)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
